default:
  image: ruby:2.6

# https://gitlab.groupprice.ru/gp-corp/devops/tree/master/ci
include:
  - project: 'gp-corp/devops'
    file: '/ci/bundler.yml'

rspec:
  stage: test
  extends:
    - .bundle_install
  script:
    - bundle exec rspec -f d

